# K Fold Cross Validation Python Code

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris = load_iris()

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2)

In [68]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.8666666666666667

In [69]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9666666666666667

In [70]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [71]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [72]:
for train_index, test_index in kf.split([11,12,13,14,15,16,17,18,19]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [73]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [76]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [81]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [83]:
for train_index, test_index in folds.split(iris.data,iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index],iris.target[train_index], iris.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [84]:
scores_logistic

[0.96, 0.96, 0.94]

In [85]:
scores_svm

[0.98, 0.98, 0.96]

In [86]:
scores_rf

[0.98, 0.94, 0.98]

In [87]:
from sklearn.model_selection import cross_val_score

In [88]:
score_lr=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

In [89]:
score_lr

array([0.96, 0.96, 0.94])

In [90]:
score_svc=cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)

In [91]:
score_svc

array([0.98, 0.98, 0.96])

In [92]:
scores_rf=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data, iris.target,cv=3)

In [94]:
scores_rf

array([0.98, 0.94, 0.96])

In [95]:
np.average(scores_rf)

0.96