# NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,5])
a

array([1, 2, 3, 5])

In [3]:
a.shape

(4,)

In [5]:
a.size

4

In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[1,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 6]])

In [9]:
b.ndim

2

In [10]:
b.shape

(4, 3)

In [11]:
b.size

12

In [12]:
b.dtype

dtype('int32')

In [13]:
b.itemsize

4

In [17]:
c=np.zeros((3,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
c=np.ones((3,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [21]:
np.arange(2,7,2) 

array([2, 4, 6])

In [22]:
np.linspace(5,10,9) 

array([ 5.   ,  5.625,  6.25 ,  6.875,  7.5  ,  8.125,  8.75 ,  9.375,
       10.   ])

In [23]:
c.reshape(5,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
c.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
d= c.ravel()
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
c.sum()

15.0

In [29]:
c.min()

1.0

In [30]:
b.max()

9

In [31]:
b.mean()

4.75

In [32]:
b.sum()

57

In [33]:
b.sum(axis=0)

array([13, 20, 24])

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 6]])

In [35]:
b.sum(axis=1)

array([ 6, 15, 24, 12])

In [36]:
np.sqrt(c)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [1.        , 2.23606798, 2.44948974]])

In [38]:
np.std(b)

2.520747243709029

In [39]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 6]])

In [40]:
d=np.array([[1, 6, 3],
       [4, 5, 9],
       [7, 4, 9],
       [1, 5, 6]])

In [41]:
d

array([[1, 6, 3],
       [4, 5, 9],
       [7, 4, 9],
       [1, 5, 6]])

In [42]:
b+d

array([[ 2,  8,  6],
       [ 8, 10, 15],
       [14, 12, 18],
       [ 2, 10, 12]])

In [43]:
b-d

array([[ 0, -4,  0],
       [ 0,  0, -3],
       [ 0,  4,  0],
       [ 0,  0,  0]])

In [44]:
b/d

array([[1.        , 0.33333333, 1.        ],
       [1.        , 1.        , 0.66666667],
       [1.        , 2.        , 1.        ],
       [1.        , 1.        , 1.        ]])

In [45]:
b.dot(d)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [46]:
d=np.array([[1,2],[3,4]])

In [47]:
e =np.array([[6,7],[1,4]])

In [48]:
d.dot(e)

array([[ 8, 15],
       [22, 37]])