In [1]:
import pandas as pd 
import numpy as np
import tensorflow as tf

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
y = df.iloc[:,-1].values

In [5]:
X = df.iloc[:,3:13].values

In [6]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()
X[:,2] = np.array(LE1.fit_transform(X[:,2]))

In [8]:
X[0]

array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
ct =ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [12]:
X[0]

array([1.0, 0.0, 1.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
ann = tf.keras.models.Sequential()

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [17]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [18]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [19]:
ann.fit(X_train,Y_train,batch_size=32,epochs = 50)

Epoch 1/50
250/250 [==============================] - 1s 2ms/step - loss: 0.6679 - accuracy: 0.6417
Epoch 2/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4955 - accuracy: 0.7968
Epoch 3/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4496 - accuracy: 0.7991
Epoch 4/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4338 - accuracy: 0.8051
Epoch 5/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4249 - accuracy: 0.8159
Epoch 6/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4160 - accuracy: 0.8209
Epoch 7/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8288
Epoch 8/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3920 - accuracy: 0.8372
Epoch 9/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3788 - accuracy: 0.8451
Epoch 10/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3686 - accuracy: 0.8499

In [23]:
print(ann.predict(sc.transform([[1.0, 0.0, 1.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88]])) > 0.5)

1/1 [==============================] - 0s 105ms/step
[[ True]]
